/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LiteIpad {
    'theme': string;
  }
  interface LiteIphoneX {
    'theme': string;
  }
  interface LiteMacBook {
    'theme': string;
  }
  interface LitePixel4 {
    'theme': string;
  }
}

declare global {


  interface HTMLLiteIpadElement extends Components.LiteIpad, HTMLStencilElement {}
  var HTMLLiteIpadElement: {
    prototype: HTMLLiteIpadElement;
    new (): HTMLLiteIpadElement;
  };

  interface HTMLLiteIphoneXElement extends Components.LiteIphoneX, HTMLStencilElement {}
  var HTMLLiteIphoneXElement: {
    prototype: HTMLLiteIphoneXElement;
    new (): HTMLLiteIphoneXElement;
  };

  interface HTMLLiteMacBookElement extends Components.LiteMacBook, HTMLStencilElement {}
  var HTMLLiteMacBookElement: {
    prototype: HTMLLiteMacBookElement;
    new (): HTMLLiteMacBookElement;
  };

  interface HTMLLitePixel4Element extends Components.LitePixel4, HTMLStencilElement {}
  var HTMLLitePixel4Element: {
    prototype: HTMLLitePixel4Element;
    new (): HTMLLitePixel4Element;
  };
  interface HTMLElementTagNameMap {
    'lite-ipad': HTMLLiteIpadElement;
    'lite-iphone-x': HTMLLiteIphoneXElement;
    'lite-mac-book': HTMLLiteMacBookElement;
    'lite-pixel-4': HTMLLitePixel4Element;
  }
}

declare namespace LocalJSX {
  interface LiteIpad {
    'theme'?: string;
  }
  interface LiteIphoneX {
    'theme'?: string;
  }
  interface LiteMacBook {
    'theme'?: string;
  }
  interface LitePixel4 {
    'theme'?: string;
  }

  interface IntrinsicElements {
    'lite-ipad': LiteIpad;
    'lite-iphone-x': LiteIphoneX;
    'lite-mac-book': LiteMacBook;
    'lite-pixel-4': LitePixel4;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lite-ipad': LocalJSX.LiteIpad & JSXBase.HTMLAttributes<HTMLLiteIpadElement>;
      'lite-iphone-x': LocalJSX.LiteIphoneX & JSXBase.HTMLAttributes<HTMLLiteIphoneXElement>;
      'lite-mac-book': LocalJSX.LiteMacBook & JSXBase.HTMLAttributes<HTMLLiteMacBookElement>;
      'lite-pixel-4': LocalJSX.LitePixel4 & JSXBase.HTMLAttributes<HTMLLitePixel4Element>;
    }
  }
}


