/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LiteIphoneFrames {
    'model': string;
    'theme': string;
  }
  interface LiteNexusFrames {}
}

declare global {


  interface HTMLLiteIphoneFramesElement extends Components.LiteIphoneFrames, HTMLStencilElement {}
  var HTMLLiteIphoneFramesElement: {
    prototype: HTMLLiteIphoneFramesElement;
    new (): HTMLLiteIphoneFramesElement;
  };

  interface HTMLLiteNexusFramesElement extends Components.LiteNexusFrames, HTMLStencilElement {}
  var HTMLLiteNexusFramesElement: {
    prototype: HTMLLiteNexusFramesElement;
    new (): HTMLLiteNexusFramesElement;
  };
  interface HTMLElementTagNameMap {
    'lite-iphone-frames': HTMLLiteIphoneFramesElement;
    'lite-nexus-frames': HTMLLiteNexusFramesElement;
  }
}

declare namespace LocalJSX {
  interface LiteIphoneFrames {
    'model'?: string;
    'theme'?: string;
  }
  interface LiteNexusFrames {}

  interface IntrinsicElements {
    'lite-iphone-frames': LiteIphoneFrames;
    'lite-nexus-frames': LiteNexusFrames;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lite-iphone-frames': LocalJSX.LiteIphoneFrames & JSXBase.HTMLAttributes<HTMLLiteIphoneFramesElement>;
      'lite-nexus-frames': LocalJSX.LiteNexusFrames & JSXBase.HTMLAttributes<HTMLLiteNexusFramesElement>;
    }
  }
}


