/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DeviceFrame {}
}

declare global {


  interface HTMLDeviceFrameElement extends Components.DeviceFrame, HTMLStencilElement {}
  var HTMLDeviceFrameElement: {
    prototype: HTMLDeviceFrameElement;
    new (): HTMLDeviceFrameElement;
  };
  interface HTMLElementTagNameMap {
    'device-frame': HTMLDeviceFrameElement;
  }
}

declare namespace LocalJSX {
  interface DeviceFrame {}

  interface IntrinsicElements {
    'device-frame': DeviceFrame;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'device-frame': LocalJSX.DeviceFrame & JSXBase.HTMLAttributes<HTMLDeviceFrameElement>;
    }
  }
}


